# Generated by Django 4.2.19 on 2025-02-28 12:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisParameters',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('buffer_radius', models.IntegerField()),
                ('weight_slope', models.FloatField()),
                ('weight_elevation', models.FloatField()),
                ('weight_wind', models.FloatField()),
                ('weight_roads', models.FloatField()),
                ('weight_landcover', models.FloatField()),
                ('weight_natura', models.FloatField()),
                ('threshold_slope', models.IntegerField()),
                ('threshold_elevation', models.IntegerField()),
                ('threshold_wind', models.FloatField()),
                ('threshold_roads', models.IntegerField()),
                ('threshold_natura', models.IntegerField()),
                ('mean_suitability', models.FloatField(blank=True, null=True)),
                ('min_suitability', models.FloatField(blank=True, null=True)),
                ('max_suitability', models.FloatField(blank=True, null=True)),
                ('suitability_map', models.TextField(blank=True, null=True)),
                ('slope_map', models.TextField(blank=True, null=True)),
                ('elevation_map', models.TextField(blank=True, null=True)),
                ('wind_speed_map', models.TextField(blank=True, null=True)),
                ('roads_map', models.TextField(blank=True, null=True)),
                ('landcover_map', models.TextField(blank=True, null=True)),
                ('natura_2000_map', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
